name: CI
on: [push, pull_request]
jobs:
  style:
    name: Style
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Check format
        run: |
          # Make sure to exit with an error if at least one file differs
          git ls-files 'content/*.md' | ( ret=0
            while read -r file
            do
              echo "Checking ${file}"
              diff --color --unified "${file}" <(sed -E 's/[[:blank:]]+$//' "${file}") || ret=$?
            done
            exit ${ret} ) || exit $?
  mkdocs:
    name: Mkdocs
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip     # install pip
          python3 -m pip install mkdocs            # install mkdocs
          python3 -m pip install mkdocs-material   # install material theme
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build site
        run: |
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    name: Deploy
    needs: mkdocs
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
